# -*- coding: utf-8 -*-
"""MarketbasketAnalysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NW8ug8aMrPLy9oND-lrug1UkKeAUUt4e
"""

!pip install pandas matplotlib seaborn mlxtend

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder

df = pd.read_csv("/content/Assignment-1_Data.csv",sep=";",decimal=",",encoding="utf-8-sig",low_memory=False)
print(df.head())
print("\nShape:", df.shape)
print("\nColumns:", df.columns.tolist())


print("\nDATA TYPES ")
print(df.dtypes)

print("\nMISSING VALUES ")
print(df.isnull().sum())

print("\nBASIC STATISTICS ")
print(df.describe())


df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)

df.dropna(subset=["CustomerID", "Itemname"], inplace=True)


df = df[~df["BillNo"].astype(str).str.startswith("C")]


df = df[df["Quantity"] > 0]

print("\n=== SHAPE AFTER CLEANING ===", df.shape)

df["Revenue"] = df["Quantity"] * df["Price"]

top_items = (df.groupby("Itemname")["Quantity"].sum().sort_values(ascending=False).head(10))
plt.figure(figsize=(12, 5))
sns.barplot(x=top_items.values, y=top_items.index, palette="Blues_d")
plt.title("Top 10 Best-Selling Items (by Quantity)")
plt.xlabel("Total Quantity Sold")
plt.ylabel("Item Name")
plt.tight_layout()
plt.savefig("top10_items.png", dpi=150)
plt.show()
print("Saved: top10_items.png")

top_countries = df["Country"].value_counts().head(10)

plt.figure(figsize=(10, 4))
sns.barplot(x=top_countries.values, y=top_countries.index, palette="Greens_d")
plt.title("Top 10 Countries by Number of Transactions")
plt.xlabel("Number of Rows")
plt.tight_layout()
plt.savefig("top10_countries.png", dpi=150)
plt.show()
print("Saved: top10_countries.png")


df["YearMonth"] = df["Date"].dt.to_period("M")
monthly_revenue = df.groupby("YearMonth")["Revenue"].sum()

plt.figure(figsize=(12, 4))
monthly_revenue.plot(kind="line", marker="o", color="steelblue")
plt.title("Monthly Revenue Trend")
plt.xlabel("Month")
plt.ylabel("Revenue (£)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("monthly_revenue.png", dpi=150)
plt.show()
print("Saved: monthly_revenue.png")

items_per_bill = df.groupby("BillNo")["Itemname"].nunique()

plt.figure(figsize=(10, 4))
sns.histplot(items_per_bill, bins=50, kde=True, color="coral")
plt.title("Distribution of Unique Items per Transaction")
plt.xlabel("Number of Unique Items")
plt.ylabel("Frequency")
plt.tight_layout()
plt.savefig("items_per_transaction.png", dpi=150)
plt.show()
print("Saved: items_per_transaction.png")

print(f"Total Transactions (Bills): {df['BillNo'].nunique()}")
print(f"Total Unique Items       : {df['Itemname'].nunique()}")
print(f"Total Customers          : {df['CustomerID'].nunique()}")
print(f"Total Countries          : {df['Country'].nunique()}")
print(f"Date Range               : {df['Date'].min()} → {df['Date'].max()}")

df_uk = df[df["Country"] == "United Kingdom"]
basket = (df_uk.groupby(["BillNo", "Itemname"])["Quantity"].sum().unstack(fill_value=0))
def encode(x):
    return 1 if x >= 1 else 0
basket_encoded = basket.applymap(encode)

print("\nBASKET SHAPE (transactions × items)")
print(basket_encoded.shape)

frequent_itemsets = apriori(basket_encoded,min_support=0.02,use_colnames=True,max_len=3          )
frequent_itemsets["length"] = frequent_itemsets["itemsets"].apply(len)

print("\nFREQUENT ITEM SETS")
print(frequent_itemsets.sort_values("support", ascending=False).head(10).to_string(index=False))

from mlxtend.frequent_patterns import association_rules
rules = association_rules(frequent_itemsets,metric="lift",min_threshold=1.0)
rules = rules.sort_values("lift", ascending=False).reset_index(drop=True)
print("\nTOP 10 ASSOCIATION RULES")
print(rules[["antecedents", "consequents", "support", "confidence", "lift"]].head(10).to_string(index=False))

plt.figure(figsize=(10, 6))
scatter = plt.scatter(rules["support"],rules["confidence"],alpha=0.6,c=rules["lift"],cmap="YlOrRd",s=rules["lift"] * 30,edgecolors="grey",linewidths=0.5)
plt.colorbar(scatter, label="Lift")
plt.title("Association Rules — Support vs Confidence\n(bubble size & colour = Lift)")
plt.xlabel("Support")
plt.ylabel("Confidence")
plt.tight_layout()
plt.savefig("rules_scatter.png", dpi=150)
plt.show()
print("Saved: rules_scatter.png")


top15 = rules.head(15).copy()
top15["rule"] = (top15["antecedents"].astype(str).str.replace("frozenset", "", regex=False)+ " → "+ top15["consequents"].astype(str).str.replace("frozenset", "", regex=False))
plt.figure(figsize=(12, 7))
sns.barplot(data=top15, x="lift", y="rule", palette="Reds_r")
plt.title("Top 15 Association Rules by Lift")
plt.xlabel("Lift")
plt.ylabel("Rule")
plt.tight_layout()
plt.savefig("top15_rules_lift.png", dpi=150)
plt.show()
print("Saved: top15_rules_lift.png")

rules[["antecedents", "consequents", "support", "confidence", "lift"]].to_csv("association_rules_output.csv", index=False)
frequent_itemsets.to_csv("frequent_itemsets_output.csv", index=False)

