# -*- coding: utf-8 -*-
"""StockPricePrediction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-CT7E-XfnvTyY-p4mHyo71YsFEAxR9eP
"""

!pip install yfinance statsmodels scikit-learn matplotlib seaborn joblib

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import seaborn as sns
import yfinance as yf
from statsmodels.tsa.stattools import adfuller, kpss
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.seasonal import seasonal_decompose
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import joblib
import os
import json
from datetime import datetime, timedelta

TICKER      = "AAPL"
START_DATE  = "2020-01-01"
END_DATE    = datetime.today().strftime("%Y-%m-%d")
TEST_SIZE   = 60
FORECAST_DAYS = 30
SAVE_DIR    = "arima_artifacts"
os.makedirs(SAVE_DIR, exist_ok=True)

raw = yf.download(TICKER, start=START_DATE, end=END_DATE, progress=False)

if raw.empty:
    raise ValueError(f"No data returned for ticker '{TICKER}'. Check the symbol.")

# Flatten MultiIndex columns that yfinance sometimes returns
if isinstance(raw.columns, pd.MultiIndex):
    raw.columns = raw.columns.get_level_values(0)

df = raw[["Open", "High", "Low", "Close", "Volume"]].copy()
df.index = pd.to_datetime(df.index)
df.sort_index(inplace=True)

print(f"   ✔ Downloaded {len(df):,} trading days  ({df.index[0].date()} → {df.index[-1].date()})\n")
print(df.tail(5))

print("\n── Descriptive Statistics (Close Price) ──")
print(df["Close"].describe().round(2))
missing = df.isnull().sum()
print(f"\Missing Values \n{missing}")
df.ffill(inplace=True)
df["Returns"]     = df["Close"].pct_change()
df["MA_20"]       = df["Close"].rolling(20).mean()
df["MA_50"]       = df["Close"].rolling(50).mean()
df["Volatility"]  = df["Returns"].rolling(20).std()
df["Log_Close"]   = np.log(df["Close"])

fig, axes = plt.subplots(3, 2, figsize=(16, 14))
fig.suptitle(f"{TICKER} — Exploratory Data Analysis", fontsize=16, fontweight="bold")

# Plot 1 – Closing price + MAs
ax = axes[0, 0]
ax.plot(df.index, df["Close"],  label="Close",  linewidth=1.2, color="#2196F3")
ax.plot(df.index, df["MA_20"],  label="MA 20",  linewidth=1,   color="#FF9800", linestyle="--")
ax.plot(df.index, df["MA_50"],  label="MA 50",  linewidth=1,   color="#E91E63", linestyle="--")
ax.set_title("Closing Price & Moving Averages"); ax.set_ylabel("Price (USD)")
ax.legend(fontsize=8); ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))

# Plot 2 – Volume
ax = axes[0, 1]
ax.bar(df.index, df["Volume"], color="#90CAF9", width=1, alpha=0.7)
ax.set_title("Trading Volume"); ax.set_ylabel("Volume")
ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))

# Plot 3 – Daily returns
ax = axes[1, 0]
ax.plot(df.index, df["Returns"], color="#4CAF50", linewidth=0.8)
ax.axhline(0, color="black", linewidth=0.8, linestyle="--")
ax.set_title("Daily Returns"); ax.set_ylabel("Return (%)")
ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))

# Plot 4 – Return distribution
ax = axes[1, 1]
df["Returns"].dropna().hist(bins=60, ax=ax, color="#7E57C2", edgecolor="white")
ax.set_title("Return Distribution"); ax.set_xlabel("Daily Return")

# Plot 5 – Rolling volatility
ax = axes[2, 0]
ax.plot(df.index, df["Volatility"], color="#F44336", linewidth=1)
ax.set_title("20-Day Rolling Volatility"); ax.set_ylabel("Std Dev of Returns")
ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))

# Plot 6 – Correlation heatmap
ax = axes[2, 1]
corr = df[["Open","High","Low","Close","Volume","Returns","Volatility"]].corr()
sns.heatmap(corr, ax=ax, annot=True, fmt=".2f", cmap="coolwarm",
            linewidths=0.5, annot_kws={"size": 7})
ax.set_title("Feature Correlation Heatmap")

plt.tight_layout()
eda_path = os.path.join(SAVE_DIR, "eda_plots.png")
plt.savefig(eda_path, dpi=150, bbox_inches="tight")
plt.close()

series = df["Close"].dropna()

def adf_test(ts, label="Series"):
    """Augmented Dickey-Fuller test."""
    result = adfuller(ts, autolag="AIC")
    stat, p, _, _, crit, _ = result
    is_stationary = p < 0.05
    print(f"\n   ── ADF Test : {label} ──")
    print(f"   ADF Statistic : {stat:.4f}")
    print(f"   p-value       : {p:.4f}")
    for k, v in crit.items():
        print(f"   Critical ({k})  : {v:.4f}")
    print(f"   → {'✔ STATIONARY' if is_stationary else '✘ NON-STATIONARY'} (p {'<' if is_stationary else '≥'} 0.05)")
    return is_stationary


stationary = adf_test(series, label="Close Price")


diff_order = 0
series_diff = series.copy()
while not stationary and diff_order < 3:
    diff_order += 1
    series_diff = series_diff.diff().dropna()
    stationary = adf_test(series_diff, label=f"Differenced (d={diff_order})")

print(f"\n   ✔ Using d = {diff_order} for ARIMA\n")

fig, axes = plt.subplots(1, 2, figsize=(14, 4))
plot_acf(series_diff,  lags=40, ax=axes[0], title="ACF  (Differenced Series)",  color="#2196F3")
plot_pacf(series_diff, lags=40, ax=axes[1], title="PACF (Differenced Series)", color="#E91E63", method="ywm")
plt.tight_layout()
acf_path = os.path.join(SAVE_DIR, "acf_pacf.png")
plt.savefig(acf_path, dpi=150, bbox_inches="tight")
plt.close()
print(f"   ✔ ACF/PACF plots saved → {acf_path}")

train_series = series[:-TEST_SIZE]   # Use only training data for order selection

best_aic = np.inf
best_order = (1, diff_order, 1)      # Sensible default fallback

for p in range(0, 4):
    for q in range(0, 4):
        try:
            model_tmp = ARIMA(train_series, order=(p, diff_order, q))
            result_tmp = model_tmp.fit()
            if result_tmp.aic < best_aic:
                best_aic   = result_tmp.aic
                best_order = (p, diff_order, q)
        except Exception:
            continue

print(f"   ✔ Best ARIMA order : {best_order}  (AIC = {best_aic:.2f})\n")

train = series[:-TEST_SIZE]
test  = series[-TEST_SIZE:]
print(f"   Train size : {len(train):,} | Test size : {len(test):,}")

arima_model  = ARIMA(train, order=best_order)
arima_result = arima_model.fit()

print("\n── Model Summary (truncated) ──")
print(arima_result.summary().tables[0])   # Print just the top info table
print()

fig = arima_result.plot_diagnostics(figsize=(14, 8))
fig.suptitle(f"ARIMA{best_order} — Residual Diagnostics", fontsize=13, fontweight="bold")
diag_path = os.path.join(SAVE_DIR, "residual_diagnostics.png")
plt.savefig(diag_path, dpi=150, bbox_inches="tight")
plt.close()
print(f"   ✔ Residual diagnostics saved → {diag_path}\n")

# ── Rolling one-step-ahead forecast on test set ───────────────────────────────
history     = list(train)
predictions = []

for t in range(len(test)):
    model_step   = ARIMA(history, order=best_order)
    result_step  = model_step.fit()
    yhat         = result_step.forecast(steps=1)[0]
    predictions.append(yhat)
    history.append(test.iloc[t])  # Append actual observation

predictions = np.array(predictions)
actuals     = test.values


mae   = mean_absolute_error(actuals, predictions)
rmse  = np.sqrt(mean_squared_error(actuals, predictions))
mape  = np.mean(np.abs((actuals - predictions) / actuals)) * 100
r2    = r2_score(actuals, predictions)

print(f"  MAE   : {mae:.4f}")
print(f"  RMSE  : {rmse:.4f}")
print(f"  MAPE  : {mape:.2f} %")
print(f"  R²    : {r2:.4f}")

final_model  = ARIMA(series, order=best_order)
final_result = final_model.fit()

forecast_obj  = final_result.get_forecast(steps=FORECAST_DAYS)
forecast_mean = forecast_obj.predicted_mean
forecast_ci   = forecast_obj.conf_int(alpha=0.05)    # 95% confidence interval

last_date       = series.index[-1]
forecast_dates  = pd.bdate_range(start=last_date + timedelta(days=1), periods=FORECAST_DAYS)
forecast_series = pd.Series(forecast_mean.values, index=forecast_dates)
ci_lower        = pd.Series(forecast_ci.iloc[:, 0].values, index=forecast_dates)
ci_upper        = pd.Series(forecast_ci.iloc[:, 1].values, index=forecast_dates)

fig, axes = plt.subplots(2, 1, figsize=(16, 12))
fig.suptitle(f"ARIMA{best_order} — {TICKER} Stock Price Prediction", fontsize=15, fontweight="bold")


ax = axes[0]
ax.plot(test.index, actuals,     label="Actual",     color="#2196F3",  linewidth=2)
ax.plot(test.index, predictions, label="Predicted",  color="#FF5722",  linewidth=1.8, linestyle="--")
ax.set_title(f"Test Set : Actual vs Predicted  (MAE={mae:.2f}, RMSE={rmse:.2f}, MAPE={mape:.2f}%)")
ax.set_ylabel("Price (USD)"); ax.legend()
ax.xaxis.set_major_formatter(mdates.DateFormatter("%b %Y"))


ax = axes[1]
lookback = 120  # Show last N days of history for context
ax.plot(series.index[-lookback:], series.values[-lookback:],
        label="Historical Close", color="#2196F3", linewidth=1.8)
ax.plot(forecast_series.index, forecast_series.values,
        label=f"Forecast ({FORECAST_DAYS} days)", color="#4CAF50", linewidth=2, marker="o", markersize=3)
ax.fill_between(forecast_series.index, ci_lower, ci_upper,
                alpha=0.25, color="#4CAF50", label="95% Confidence Interval")
ax.axvline(x=series.index[-1], color="grey", linestyle="--", linewidth=1, label="Forecast Start")
ax.set_title(f"Future {FORECAST_DAYS}-Day Price Forecast")
ax.set_ylabel("Price (USD)"); ax.legend()
ax.xaxis.set_major_formatter(mdates.DateFormatter("%b %Y"))

plt.tight_layout()
forecast_path = os.path.join(SAVE_DIR, "forecast_plot.png")
plt.savefig(forecast_path, dpi=150, bbox_inches="tight")
plt.close()
print(f"   ✔ Forecast plot saved → {forecast_path}\n")


print("── Forecasted Prices ──")
forecast_df = pd.DataFrame({
    "Date"      : forecast_series.index,
    "Forecast"  : forecast_series.values.round(2),
    "Lower_95"  : ci_lower.values.round(2),
    "Upper_95"  : ci_upper.values.round(2),
})
print(forecast_df.to_string(index=False))
forecast_df.to_csv(os.path.join(SAVE_DIR, "forecast_values.csv"), index=False)
print(f"\n   ✔ Forecast CSV saved → {SAVE_DIR}/forecast_values.csv\n")

model_path = os.path.join(SAVE_DIR, "arima_model.pkl")
joblib.dump(final_result, model_path)
print(f"   ✔ Model saved     → {model_path}")