# -*- coding: utf-8 -*-
"""CreditCardFraudData

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19p5zyqWbxn-F_qd6mIBPIbYS18R8_beN
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/fraudTest.csv")
print(df.head(5))

print(df.describe())

df.info()

print(f"Column names: {df.columns}")
print(f"Dataset Shape : {df.shape}")

# Class Imbalance
print(print(df['is_fraud'].value_counts()))
sns.countplot(x='is_fraud', data=df)
plt.title('Target Class Distribution')
plt.show()

fraud_percent = (df['is_fraud'].mean())*100

print(f"Fraud Rate: {fraud_percent:.4f}%")

print(f"Missing values :\n{df.isna().sum()}")

sns.boxplot(x='is_fraud', y='amt',data=df)

sns.histplot(np.log1p(df['amt']), bins=100)
plt.show()

df['category'].value_counts()

fraud_by_category = df.groupby('category')['is_fraud'].mean()
fraud_by_category.sort_values( ascending=False)

pd.crosstab(df['gender'],df['is_fraud'])

sns.countplot(x='gender',hue='is_fraud',data=df)

state_fraud = (df.groupby('state')['is_fraud'].mean().sort_values(ascending=False))
print(state_fraud.head(10))

df['dob'] = pd.to_datetime(df['dob'])

df['age'] = (pd.Timestamp.now()- df['dob']).dt.days // 365

df.to_csv("PreprocessedData.csv", index=False)