# -*- coding: utf-8 -*-
"""Assignment3_HousePriceEDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yuhVggeOzF5O7pwNu-Iua6-r5y8ezYSp
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/clean_data.csv")
df.head(10)

df.columns

df.info()

df.describe()

print(f"Total missing values in each columns \n {df.isnull().sum()}")

df.dtypes

"""**IMPUTATION FOR AGE**  """

df['age'].value_counts()

df['age'].hist(bins=20)
plt.xlabel("Property Age")
plt.ylabel("Frequency")
plt.title("Distribution of Property Age")
plt.show()

df['age'].fillna(df['age'].median(), inplace=True)

print(df['age'].isnull().sum())

"""**IMPUTATION FOR NUMBER OF BATHROOM**"""

df['bathroom'].value_counts()

df['bathroom'].hist(bins=9)
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.title("Distribution of Bathroom Counts")
plt.show()

print(df['bathroom'].isnull().sum())

df['bathroom'] = df.groupby('bhk')['bathroom'].transform(lambda x: x.fillna(x.median()))

"""**CATEGORICAL COLUMNS**"""

df['status'].value_counts()

df['location'].value_counts().head(5)

df['builder'].value_counts().head(5)

plt.title("Property Price vs. Area")
sns.scatterplot(x='area', y='price', data=df)

plt.title("Property Price vs. bhk")
sns.scatterplot(x='bhk', y='price', data=df)

plt.title("Property Price vs. Age")
sns.scatterplot(x='age', y='price', data=df)

"""**OUTLIER DETECTION**"""

plt.figure(figsize=(8,4))
sns.boxplot(x=df['price'])
plt.title("Price Outliers")
plt.show()

plt.figure(figsize=(8,4))
sns.boxplot(y=df['area'])
plt.title("Area Outliers")
plt.show()

plt.figure(figsize=(8,4))
sns.boxplot(y=df['bathroom'])
plt.title("Bathroom Outliers")
plt.show()

cols = ['price','area','bathroom','age','bhk']

for col in cols:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    l = Q1 - 1.5 * IQR
    u = Q3 + 1.5 * IQR

    df = df[(df[col] >= l) & (df[col] <= u)]

print("Shape after outlier removal :", df.shape)

plt.figure(figsize=(8,4))

sns.barplot(
    x='bhk',
    y='price',
    data=df
)

plt.title("Average Price by BHK")
plt.show()

plt.figure(figsize=(8,4))

sns.barplot(
    x='status',
    y='price',
    data=df
)

plt.xticks(rotation=20)
plt.title("Average Price by Status")
plt.show()



df['price_per_sqft'] = (df['price'] * 100000) / df['area']
print(df['price_per_sqft'])